// bpmf.lead.v1 is the sales lead collection API, the entry point of the
// bpmf sales funnel.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: bpmf/lead/v1/lead.proto

package leadv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeadService_SubmitLead_FullMethodName = "/bpmf.lead.v1.LeadService/SubmitLead"
)

// LeadServiceClient is the client API for LeadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LeadService collects sales leads from public channels. It is the single
// entry point of the sales funnel MVP.
type LeadServiceClient interface {
	// Submits a sales lead.
	//
	// Leads are qualified downstream: high-value leads (e.g. large companies
	// or strong intent signals) are routed to human follow-up, while the rest
	// enter the self-service nurture flow.
	//
	// Returns the stored lead in `lead`, including its server-assigned `name`
	// and `create_time`. Returns INVALID_ARGUMENT if `lead` is missing or misses
	// required fields. Returns RESOURCE_EXHAUSTED if the caller is rate
	// limited.
	SubmitLead(ctx context.Context, in *SubmitLeadRequest, opts ...grpc.CallOption) (*SubmitLeadResponse, error)
}

type leadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeadServiceClient(cc grpc.ClientConnInterface) LeadServiceClient {
	return &leadServiceClient{cc}
}

func (c *leadServiceClient) SubmitLead(ctx context.Context, in *SubmitLeadRequest, opts ...grpc.CallOption) (*SubmitLeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitLeadResponse)
	err := c.cc.Invoke(ctx, LeadService_SubmitLead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeadServiceServer is the server API for LeadService service.
// All implementations must embed UnimplementedLeadServiceServer
// for forward compatibility.
//
// LeadService collects sales leads from public channels. It is the single
// entry point of the sales funnel MVP.
type LeadServiceServer interface {
	// Submits a sales lead.
	//
	// Leads are qualified downstream: high-value leads (e.g. large companies
	// or strong intent signals) are routed to human follow-up, while the rest
	// enter the self-service nurture flow.
	//
	// Returns the stored lead in `lead`, including its server-assigned `name`
	// and `create_time`. Returns INVALID_ARGUMENT if `lead` is missing or misses
	// required fields. Returns RESOURCE_EXHAUSTED if the caller is rate
	// limited.
	SubmitLead(context.Context, *SubmitLeadRequest) (*SubmitLeadResponse, error)
	mustEmbedUnimplementedLeadServiceServer()
}

// UnimplementedLeadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeadServiceServer struct{}

func (UnimplementedLeadServiceServer) SubmitLead(context.Context, *SubmitLeadRequest) (*SubmitLeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitLead not implemented")
}
func (UnimplementedLeadServiceServer) mustEmbedUnimplementedLeadServiceServer() {}
func (UnimplementedLeadServiceServer) testEmbeddedByValue()                     {}

// UnsafeLeadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeadServiceServer will
// result in compilation errors.
type UnsafeLeadServiceServer interface {
	mustEmbedUnimplementedLeadServiceServer()
}

func RegisterLeadServiceServer(s grpc.ServiceRegistrar, srv LeadServiceServer) {
	// If the following call panics, it indicates UnimplementedLeadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeadService_ServiceDesc, srv)
}

func _LeadService_SubmitLead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitLeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeadServiceServer).SubmitLead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeadService_SubmitLead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeadServiceServer).SubmitLead(ctx, req.(*SubmitLeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeadService_ServiceDesc is the grpc.ServiceDesc for LeadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bpmf.lead.v1.LeadService",
	HandlerType: (*LeadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitLead",
			Handler:    _LeadService_SubmitLead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bpmf/lead/v1/lead.proto",
}
