// bpmf.lead.v1 is the sales lead collection API, the entry point of the
// bpmf sales funnel.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: bpmf/lead/v1/lead.proto

package leadv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompanySize is the size of a prospect company by employee count.
type CompanySize int32

const (
	// Company size not specified.
	CompanySize_COMPANY_SIZE_UNSPECIFIED CompanySize = 0
	// 1 to 9 employees.
	CompanySize_COMPANY_SIZE_MICRO CompanySize = 1
	// 10 to 49 employees.
	CompanySize_COMPANY_SIZE_SMALL CompanySize = 2
	// 50 to 249 employees.
	CompanySize_COMPANY_SIZE_MEDIUM CompanySize = 3
	// 250 to 999 employees.
	CompanySize_COMPANY_SIZE_LARGE CompanySize = 4
	// 1000 or more employees.
	CompanySize_COMPANY_SIZE_ENTERPRISE CompanySize = 5
)

// Enum value maps for CompanySize.
var (
	CompanySize_name = map[int32]string{
		0: "COMPANY_SIZE_UNSPECIFIED",
		1: "COMPANY_SIZE_MICRO",
		2: "COMPANY_SIZE_SMALL",
		3: "COMPANY_SIZE_MEDIUM",
		4: "COMPANY_SIZE_LARGE",
		5: "COMPANY_SIZE_ENTERPRISE",
	}
	CompanySize_value = map[string]int32{
		"COMPANY_SIZE_UNSPECIFIED": 0,
		"COMPANY_SIZE_MICRO":       1,
		"COMPANY_SIZE_SMALL":       2,
		"COMPANY_SIZE_MEDIUM":      3,
		"COMPANY_SIZE_LARGE":       4,
		"COMPANY_SIZE_ENTERPRISE":  5,
	}
)

func (x CompanySize) Enum() *CompanySize {
	p := new(CompanySize)
	*p = x
	return p
}

func (x CompanySize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompanySize) Descriptor() protoreflect.EnumDescriptor {
	return file_bpmf_lead_v1_lead_proto_enumTypes[0].Descriptor()
}

func (CompanySize) Type() protoreflect.EnumType {
	return &file_bpmf_lead_v1_lead_proto_enumTypes[0]
}

func (x CompanySize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompanySize.Descriptor instead.
func (CompanySize) EnumDescriptor() ([]byte, []int) {
	return file_bpmf_lead_v1_lead_proto_rawDescGZIP(), []int{0}
}

// Channel is the public channel a lead was collected from.
type Channel int32

const (
	// Channel not specified.
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	// The product website, e.g. a "request a trial" form.
	Channel_CHANNEL_WEBSITE Channel = 1
	// WeCom (企业微信), e.g. a staff conversation or a QR code entry.
	Channel_CHANNEL_WECOM Channel = 2
	// A referral from an existing customer or partner.
	Channel_CHANNEL_REFERRAL Channel = 3
	// A community space such as a forum or a chat group.
	Channel_CHANNEL_COMMUNITY Channel = 4
	// A channel not covered by the values above.
	Channel_CHANNEL_OTHER Channel = 5
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_WEBSITE",
		2: "CHANNEL_WECOM",
		3: "CHANNEL_REFERRAL",
		4: "CHANNEL_COMMUNITY",
		5: "CHANNEL_OTHER",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_WEBSITE":     1,
		"CHANNEL_WECOM":       2,
		"CHANNEL_REFERRAL":    3,
		"CHANNEL_COMMUNITY":   4,
		"CHANNEL_OTHER":       5,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_bpmf_lead_v1_lead_proto_enumTypes[1].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_bpmf_lead_v1_lead_proto_enumTypes[1]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_bpmf_lead_v1_lead_proto_rawDescGZIP(), []int{1}
}

// Lead is a sales prospect collected from a public marketing channel.
//
// A lead carries the contact information needed for follow-up, plus the
// channel attribution needed to measure promotion cost per channel.
type Lead struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name of the lead, in the form `leads/{lead}`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Company name of the prospect.
	Company string `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	// Name of the contact person at the prospect company.
	ContactName string `protobuf:"bytes,3,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	// Email address of the contact person.
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// Phone number of the contact person, preferably in E.164 format.
	Phone string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	// Size of the prospect company, used to qualify leads for human
	// follow-up in the mixed sales model.
	CompanySize CompanySize `protobuf:"varint,6,opt,name=company_size,json=companySize,proto3,enum=bpmf.lead.v1.CompanySize" json:"company_size,omitempty"`
	// Free-form message from the prospect describing their needs.
	Message string `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	// Channel the lead was collected from.
	Channel Channel `protobuf:"varint,8,opt,name=channel,proto3,enum=bpmf.lead.v1.Channel" json:"channel,omitempty"`
	// UTM source of the first marketing touch that led to this submission,
	// used for channel attribution and promotion cost analysis.
	UtmSource string `protobuf:"bytes,9,opt,name=utm_source,json=utmSource,proto3" json:"utm_source,omitempty"`
	// UTM medium of the first marketing touch.
	UtmMedium string `protobuf:"bytes,10,opt,name=utm_medium,json=utmMedium,proto3" json:"utm_medium,omitempty"`
	// UTM campaign of the first marketing touch.
	UtmCampaign string `protobuf:"bytes,11,opt,name=utm_campaign,json=utmCampaign,proto3" json:"utm_campaign,omitempty"`
	// Time the lead was submitted.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lead) Reset() {
	*x = Lead{}
	mi := &file_bpmf_lead_v1_lead_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lead) ProtoMessage() {}

func (x *Lead) ProtoReflect() protoreflect.Message {
	mi := &file_bpmf_lead_v1_lead_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lead.ProtoReflect.Descriptor instead.
func (*Lead) Descriptor() ([]byte, []int) {
	return file_bpmf_lead_v1_lead_proto_rawDescGZIP(), []int{0}
}

func (x *Lead) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lead) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Lead) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *Lead) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Lead) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Lead) GetCompanySize() CompanySize {
	if x != nil {
		return x.CompanySize
	}
	return CompanySize_COMPANY_SIZE_UNSPECIFIED
}

func (x *Lead) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Lead) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *Lead) GetUtmSource() string {
	if x != nil {
		return x.UtmSource
	}
	return ""
}

func (x *Lead) GetUtmMedium() string {
	if x != nil {
		return x.UtmMedium
	}
	return ""
}

func (x *Lead) GetUtmCampaign() string {
	if x != nil {
		return x.UtmCampaign
	}
	return ""
}

func (x *Lead) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// SubmitLeadRequest is the request message for LeadService.SubmitLead.
type SubmitLeadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The lead to submit. `company`, `email`, and `channel` are required;
	// all other fields are optional.
	Lead *Lead `protobuf:"bytes,1,opt,name=lead,proto3" json:"lead,omitempty"`
	// Client-generated id for this submission, used to de-duplicate repeated
	// form posts (e.g. a double click or a retry). Re-submitting the same
	// `request_id` returns the original lead instead of creating a duplicate.
	RequestId     string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitLeadRequest) Reset() {
	*x = SubmitLeadRequest{}
	mi := &file_bpmf_lead_v1_lead_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitLeadRequest) ProtoMessage() {}

func (x *SubmitLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpmf_lead_v1_lead_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitLeadRequest.ProtoReflect.Descriptor instead.
func (*SubmitLeadRequest) Descriptor() ([]byte, []int) {
	return file_bpmf_lead_v1_lead_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitLeadRequest) GetLead() *Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

func (x *SubmitLeadRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// SubmitLeadResponse is the response message for LeadService.SubmitLead.
type SubmitLeadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stored lead, including its server-assigned `name` and `create_time`.
	Lead          *Lead `protobuf:"bytes,1,opt,name=lead,proto3" json:"lead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitLeadResponse) Reset() {
	*x = SubmitLeadResponse{}
	mi := &file_bpmf_lead_v1_lead_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitLeadResponse) ProtoMessage() {}

func (x *SubmitLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpmf_lead_v1_lead_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitLeadResponse.ProtoReflect.Descriptor instead.
func (*SubmitLeadResponse) Descriptor() ([]byte, []int) {
	return file_bpmf_lead_v1_lead_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitLeadResponse) GetLead() *Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

var File_bpmf_lead_v1_lead_proto protoreflect.FileDescriptor

const file_bpmf_lead_v1_lead_proto_rawDesc = "" +
	"\n" +
	"\x17bpmf/lead/v1/lead.proto\x12\fbpmf.lead.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x03\n" +
	"\x04Lead\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12\x1d\n" +
	"\acompany\x18\x02 \x01(\tB\x03\xe0A\x02R\acompany\x12!\n" +
	"\fcontact_name\x18\x03 \x01(\tR\vcontactName\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tB\x03\xe0A\x02R\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12<\n" +
	"\fcompany_size\x18\x06 \x01(\x0e2\x19.bpmf.lead.v1.CompanySizeR\vcompanySize\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x124\n" +
	"\achannel\x18\b \x01(\x0e2\x15.bpmf.lead.v1.ChannelB\x03\xe0A\x02R\achannel\x12\x1d\n" +
	"\n" +
	"utm_source\x18\t \x01(\tR\tutmSource\x12\x1d\n" +
	"\n" +
	"utm_medium\x18\n" +
	" \x01(\tR\tutmMedium\x12!\n" +
	"\futm_campaign\x18\v \x01(\tR\vutmCampaign\x12@\n" +
	"\vcreate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\"_\n" +
	"\x11SubmitLeadRequest\x12+\n" +
	"\x04lead\x18\x01 \x01(\v2\x12.bpmf.lead.v1.LeadB\x03\xe0A\x02R\x04lead\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"A\n" +
	"\x12SubmitLeadResponse\x12+\n" +
	"\x04lead\x18\x01 \x01(\v2\x12.bpmf.lead.v1.LeadB\x03\xe0A\x02R\x04lead*\xa9\x01\n" +
	"\vCompanySize\x12\x1c\n" +
	"\x18COMPANY_SIZE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12COMPANY_SIZE_MICRO\x10\x01\x12\x16\n" +
	"\x12COMPANY_SIZE_SMALL\x10\x02\x12\x17\n" +
	"\x13COMPANY_SIZE_MEDIUM\x10\x03\x12\x16\n" +
	"\x12COMPANY_SIZE_LARGE\x10\x04\x12\x1b\n" +
	"\x17COMPANY_SIZE_ENTERPRISE\x10\x05*\x8a\x01\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCHANNEL_WEBSITE\x10\x01\x12\x11\n" +
	"\rCHANNEL_WECOM\x10\x02\x12\x14\n" +
	"\x10CHANNEL_REFERRAL\x10\x03\x12\x15\n" +
	"\x11CHANNEL_COMMUNITY\x10\x04\x12\x11\n" +
	"\rCHANNEL_OTHER\x10\x052^\n" +
	"\vLeadService\x12O\n" +
	"\n" +
	"SubmitLead\x12\x1f.bpmf.lead.v1.SubmitLeadRequest\x1a .bpmf.lead.v1.SubmitLeadResponseB!Z\x1fbpmf.io/api/bpmf/lead/v1;leadv1b\x06proto3"

var (
	file_bpmf_lead_v1_lead_proto_rawDescOnce sync.Once
	file_bpmf_lead_v1_lead_proto_rawDescData []byte
)

func file_bpmf_lead_v1_lead_proto_rawDescGZIP() []byte {
	file_bpmf_lead_v1_lead_proto_rawDescOnce.Do(func() {
		file_bpmf_lead_v1_lead_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bpmf_lead_v1_lead_proto_rawDesc), len(file_bpmf_lead_v1_lead_proto_rawDesc)))
	})
	return file_bpmf_lead_v1_lead_proto_rawDescData
}

var file_bpmf_lead_v1_lead_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bpmf_lead_v1_lead_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bpmf_lead_v1_lead_proto_goTypes = []any{
	(CompanySize)(0),              // 0: bpmf.lead.v1.CompanySize
	(Channel)(0),                  // 1: bpmf.lead.v1.Channel
	(*Lead)(nil),                  // 2: bpmf.lead.v1.Lead
	(*SubmitLeadRequest)(nil),     // 3: bpmf.lead.v1.SubmitLeadRequest
	(*SubmitLeadResponse)(nil),    // 4: bpmf.lead.v1.SubmitLeadResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_bpmf_lead_v1_lead_proto_depIdxs = []int32{
	0, // 0: bpmf.lead.v1.Lead.company_size:type_name -> bpmf.lead.v1.CompanySize
	1, // 1: bpmf.lead.v1.Lead.channel:type_name -> bpmf.lead.v1.Channel
	5, // 2: bpmf.lead.v1.Lead.create_time:type_name -> google.protobuf.Timestamp
	2, // 3: bpmf.lead.v1.SubmitLeadRequest.lead:type_name -> bpmf.lead.v1.Lead
	2, // 4: bpmf.lead.v1.SubmitLeadResponse.lead:type_name -> bpmf.lead.v1.Lead
	3, // 5: bpmf.lead.v1.LeadService.SubmitLead:input_type -> bpmf.lead.v1.SubmitLeadRequest
	4, // 6: bpmf.lead.v1.LeadService.SubmitLead:output_type -> bpmf.lead.v1.SubmitLeadResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_bpmf_lead_v1_lead_proto_init() }
func file_bpmf_lead_v1_lead_proto_init() {
	if File_bpmf_lead_v1_lead_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bpmf_lead_v1_lead_proto_rawDesc), len(file_bpmf_lead_v1_lead_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bpmf_lead_v1_lead_proto_goTypes,
		DependencyIndexes: file_bpmf_lead_v1_lead_proto_depIdxs,
		EnumInfos:         file_bpmf_lead_v1_lead_proto_enumTypes,
		MessageInfos:      file_bpmf_lead_v1_lead_proto_msgTypes,
	}.Build()
	File_bpmf_lead_v1_lead_proto = out.File
	file_bpmf_lead_v1_lead_proto_goTypes = nil
	file_bpmf_lead_v1_lead_proto_depIdxs = nil
}
